# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ff2c224ee7da96472d3a885804c73f60252d1bc6cbddece6e0a4be897b1fdc2740c9227713d841a15d4fb33469e3685144c3655bb55eba1acd0012f54e5685

test:
  secret_key_base: 0fcf09b07051ef79b1a927a3e814b879416b65dfdc959c105847ba8d711bc2732c3b4389b8b391f19419ec81d3fbabad8defd730fff487ec2dd742f7e6c5f27e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
